services:
  pgvector_db:
    image: pgvector/pgvector:pg14
    # user: "1000:1000"
    environment:
      POSTGRES_USER: pgvector_user
      POSTGRES_PASSWORD: pgvector_password
      POSTGRES_DB: pgvector_database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
