[tool.poetry]
name = "arxiv2arxode"
version = "0.1.0"
description = "Undergrad research project"
authors = ["Abdulla <abdullabloushi@gmail.com>"]
license = "UNLICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.3.4"
pydantic = "^2.5.2"
isort = "^5.12.0"
langchain = "^0.0.341"
nest-asyncio = "^1.5.8"
chromadb = "^0.4.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
