[tool.poetry]
name = "arxiv2arxode"
version = "0.1.0"
description = "Undergrad research project"
authors = ["Abdulla <abdullabloushi@gmail.com>"]
license = "UNLICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
openai = "^1.3.4"
pydantic = "^2.5.2"
isort = "^5.12.0"
langchain = "^0.0.341"
nest-asyncio = "^1.5.8"
chromadb = "^0.4.18"
diskcache = "^5.6.3"
pyautogen = "^0.2.2"
pypdf = "^3.17.4"
pyscopg2 = "^66.0.2"
pgvector = "^0.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
