[tool.poetry]
name = "arxiv2arxode"
version = "0.1.0"
description = "Undergrad research project"
authors = ["Abdulla <abdullabloushi@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
