name: beautify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11","3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
      - name: isort
        run: |
          isort $(git ls-files '*.py')
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: lint with black
        run: |
          black $(git ls-files '*.py')
